version: "3"
services:
  tegola:
    image: gospatial/tegola
    command: serve --config /tegola_config/config.toml
    ports:
        - 7080:8080
    volumes:
        - ./tegola_config:/tegola_config
    depends_on:
        - db
  db:
    image: postgis/postgis
    volumes:
        - ./db:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: map
        POSTGRES_USER: postgres
        ALLOW_IP_RANGE: 0.0.0.0/0
  pgadmin4:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: 1060950782@163.com
        PGADMIN_DEFAULT_PASSWORD: admin
    ports:
        - 7088:80
    depends_on:
        - db